/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnidemojava_PassSringJtoC */

#ifndef _Included_jnidemojava_PassSringJtoC
#define _Included_jnidemojava_PassSringJtoC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnidemojava_PassSringJtoC
 * Method:    print
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jnidemojava_PassSringJtoC_print
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
