/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnidemojava_HelloWorld */

#ifndef _Included_jnidemojava_HelloWorld
#define _Included_jnidemojava_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnidemojava_HelloWorld
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnidemojava_HelloWorld_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
