/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnidemojava_JNIDemoJava */

#ifndef _Included_jnidemojava_JNIDemoJava
#define _Included_jnidemojava_JNIDemoJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnidemojava_JNIDemoJava
 * Method:    nativePrint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnidemojava_JNIDemoJava_nativePrint
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
